config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: { message: "Enter your task!" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task = Task.find(params[:id])
    @task.update(completed: params[:completed])
  
    render json: { message: "Success" }
  end
  
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully deleted."
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "form-container", data: { controller: "task-form", action: "submit->task-form#validateOnSubmit" }) do |form| %>
  <div class="input-container">
    <%= form.text_field :description, placeholder: "Add new task", class: "input-field", 
        data: { 
            task_form_target: "input", 
            action: "input->task-form#hideError" 
        } 
    %>
    
    <% if task.errors.any? %>
      <div class="error-message">
        <%= task.errors.full_messages_for(:description).first %>
      </div>
    <% end %>
    
    <% btn_class = task.description.present? ? "btn btn-primary" : "btn btn-disabled" %>
    <%= form.submit "Save", class: btn_class, data: { task_form_target: "submitButton" } %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li class="task-item">
  <%= form_with(model: task, class: "task-description") do |form| %>
    <%= form.check_box :completed,
                     data: {
                       id: task.id,
                       action: "tasks#toggle"
                     },
                     class: "task-checkbox" %>
    <p class="task-text"><%= task.description %></p>
  <% end %>

  <div class="task-actions">
    <%= link_to "Edit", edit_task_path(task),
              class: "btn btn-secondary btn-small" %>
    
    <%= button_to "Delete", task_path(task),
                method: :delete,
                data: { action: "tasks#delete" },
                class: "btn btn-danger btn-small" %>
  </div>
</li>

app/views/tasks/edit.html.erb
<!-- Edit page -->
<div class="edit-container">
  <h1 class="page-title">Editing Task</h1>

  <div id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/tasks/index.html.erb
<!-- Index page -->
<div data-controller="notification">
  <% if notice.present? %>
    <p class="notification notification-success" id="notice" data-notification-target="notification">
      <%= notice %>
    </p>
  <% end %>
</div>

<div class="container">
  <h1 class="page-title">Task Manager</h1>

  <%= render "form", task: @task %>

  <div id="tasks" class="task-container">
    <h1 class="section-title">Tasks</h1>

    <ul class="task-list" data-controller="tasks">
      <%= render @tasks %>
    </ul>
  </div>
</div>